version: '3.8'

volumes:
  pg_balancehub:
    name: pg_balancehub_db_volume
    external: false
  es_data:
    name: es_data_volume
    external: false

networks:
  balancehub_net:
    driver: bridge

services:
  balancehub_db:
    container_name: ${BALANCE_HUB_DB_NAME}
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${BALANCE_HUB_DB_USER}
      - POSTGRES_PASSWORD=${BALANCE_HUB_DB_PASSWORD}
      - POSTGRES_DB=${BALANCE_HUB_DB_NAME}
    volumes:
      - pg_balancehub:/var/lib/postgresql/data
    ports:
      - ${BALANCE_HUB_DB_HOST}:${BALANCE_HUB_DB_EPORT}:${BALANCE_HUB_DB_PORT}
    networks:
      - balancehub_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${BALANCE_HUB_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    ports:
      - ${REDIS_PORT_EPORT}:${REDIS_PORT}
    networks:
      - balancehub_net
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - ${ELASTIC_HTTP_API_PORT}
      - ${ELASTIC_HTTP_TRANSPORT_PORT}
    restart: always
    networks:
      - balancehub_net
    healthcheck:
      test: curl -u elastic:${ELASTIC_PASSWORD} --silent --fail http://localhost:9200/_cluster/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 10

  balancehub:
    container_name: balancehub
    restart: no
    build:
      context: ${APP_PATH}
      dockerfile: Dockerfile
    ports:
      - ${BALANCE_HUB_APP_EPORT}:${BALANCE_HUB_APP_PORT}
    depends_on:
      balancehub_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_APPLICATION_JSON: ${SPRING_APPLICATION_PARAMS}
      JAVA_OPTS: ${JV_MAX_MEM}
    networks:
      - balancehub_net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
