CREATE TABLE USER (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(500),
    DATE_OF_BIRTH DATE,
    PASSWORD VARCHAR(500)
);

CREATE TABLE ACCOUNT (
    ID BIGINT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    BALANCE DECIMAL,
    CONSTRAINT FK_ACCOUNT_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE EMAIL_DATA (
    ID BIGINT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    EMAIL VARCHAR(200) UNIQUE,
    CONSTRAINT FK_EMAIL_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE PHONE_DATA (
    ID BIGINT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    PHONE VARCHAR(13) UNIQUE,
    CONSTRAINT FK_PHONE_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);
