CREATE SEQUENCE user_id_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE USERS
(
    ID            BIGINT PRIMARY KEY,
    NAME          VARCHAR(500),
    DATE_OF_BIRTH DATE,
    PASSWORD      VARCHAR(500)
);

CREATE SEQUENCE account_id_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE ACCOUNTS
(
    ID      BIGINT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    BALANCE DECIMAL,
    CONSTRAINT FK_ACCOUNT_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE SEQUENCE email_data_id_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE EMAIL_DATA
(
    ID      BIGINT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    EMAIL   VARCHAR(200) UNIQUE,
    CONSTRAINT FK_EMAIL_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE SEQUENCE phone_data_id_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE PHONE_DATA
(
    ID      BIGINT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    PHONE_NUMBER   VARCHAR(13) UNIQUE,
    CONSTRAINT FK_PHONE_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);
